// Command notices writes THIRD_PARTY_NOTICES: the copyright notices and
// license texts of every module compiled into sipbxgo on any supported
// platform, plus the Go standard library. MIT and BSD licenses require these to accompany any
// distribution of the software.
//
//	go run ./tools/notices > THIRD_PARTY_NOTICES
//
// CI regenerates the file and fails if it is out of date.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type module struct{ path, version, dir string }

// licenseFile matches LICENSE, LICENSE-SQLITE, COPYING.md, NOTICE,
// PATENTS, AUTHORS and similar; files in a LICENSES/ directory (the REUSE
// convention) are included too.
var licenseFile = regexp.MustCompile(`(?i)^(licen[cs]es?|copying|notice|patents|authors)([-_.][\w.-]*)?$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run() error {
	mods, err := modules()
	if err != nil {
		return err
	}
	goroot, err := output("go", "env", "GOROOT")
	if err != nil {
		return err
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprint(w, `THIRD-PARTY SOFTWARE NOTICES

SIPBXGO is licensed under the Apache License, Version 2.0 (see LICENSE).
It includes the following third-party software, each under its own license.
The copyright notices and license texts below are reproduced as those
licenses require. This file is generated by "go run ./tools/notices".
`)
	write := func(name, version, dir string) error {
		files, err := licenseFiles(dir)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			return fmt.Errorf("%s: no license file found in %s", name, dir)
		}
		fmt.Fprintf(w, "\n%s\n%s", strings.Repeat("=", 78), name)
		if version != "" {
			fmt.Fprintf(w, " %s", version)
		}
		fmt.Fprintln(w)
		for _, f := range files {
			text, err := os.ReadFile(filepath.Join(dir, f))
			if err != nil {
				return err
			}
			text = bytes.ReplaceAll(text, []byte("\r\n"), []byte("\n"))
			fmt.Fprintf(w, "%s\n-- %s --\n\n%s\n", strings.Repeat("=", 78), f, bytes.TrimSpace(text))
		}
		return nil
	}
	if err := write("The Go Programming Language (standard library and runtime)", "", goroot); err != nil {
		return err
	}
	for _, m := range mods {
		if err := write(m.path, m.version, m.dir); err != nil {
			return err
		}
	}
	return nil
}

// platforms are the targets sipbxgo may be built for. A few modules are
// only linked on some of them (e.g. terminal detection on Windows), so the
// notices cover the union: the file is then identical wherever it is
// generated, and correct for any build.
var platforms = [][2]string{
	{"linux", "amd64"}, {"linux", "arm64"},
	{"windows", "amd64"}, {"windows", "arm64"},
	{"darwin", "amd64"}, {"darwin", "arm64"},
}

// modules lists the non-main modules linked into cmd/sipbxgo on any
// supported platform.
func modules() ([]module, error) {
	seen := map[string]bool{}
	var mods []module
	for _, pl := range platforms {
		cmd := exec.Command("go", "list", "-deps",
			"-f", `{{with .Module}}{{if not .Main}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}{{end}}`,
			"./cmd/sipbxgo")
		cmd.Env = append(os.Environ(), "GOOS="+pl[0], "GOARCH="+pl[1], "CGO_ENABLED=0")
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		if err != nil {
			return nil, fmt.Errorf("go list for %s/%s: %w", pl[0], pl[1], err)
		}
		for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
			f := strings.Split(line, "\t")
			if len(f) != 3 || seen[f[0]] {
				continue
			}
			seen[f[0]] = true
			mods = append(mods, module{f[0], f[1], f[2]})
		}
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].path < mods[j].path })
	return mods, nil
}

func licenseFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		switch {
		case e.IsDir() && strings.EqualFold(e.Name(), "LICENSES"):
			sub, err := os.ReadDir(filepath.Join(dir, e.Name()))
			if err != nil {
				return nil, err
			}
			for _, f := range sub {
				if !f.IsDir() {
					files = append(files, e.Name()+"/"+f.Name())
				}
			}
		case !e.IsDir() && licenseFile.MatchString(e.Name()):
			files = append(files, e.Name())
		}
	}
	sort.Strings(files)
	return files, nil
}

func output(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	return strings.TrimSpace(string(out)), err
}
